sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_201d61b8139d_key -iv $encrypted_201d61b8139d_iv -in multi-k8s-284922-fce35bb8f9f5.json.enc -out multi-k8s-284922-fce35bb8f9f5.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json


script:
  - docker run -e CI=true luisnajera/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-335782550487"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY